import Head from 'next/head'
import Image from "next/image"
import { useRef } from 'react'
import { use100vh } from "react-div-100vh";
import ReactTypingEffect from 'react-typing-effect';
import ThreeScene from "../components/threeScene";
import { motion, useMotionTemplate, motionValue, useTransform, useViewportScroll, useElementScroll } from "framer-motion";
import { useProgress } from "@react-three/drei";
import Morph from "../components/Morph";
import useRefScrollProgress from "../hooks/refViewportProgress";
import About from "../components/About";
import Skills from "../components/Skills";
import Portfolio from "../components/Portfolio";
import Hero from "../components/Hero";

export default function Home() {

    // <div className="flex flex-col gap-4 items-center">
    //     <div className="flex gap-4">
    //         <a href="https://www.linkedin.com/in/mijaelfv/">
    //             <Image src={"/assets/linkedin.svg"} height={30} width={30} className="cursor-pointer" alt="linkedin profile" />
    //         </a>
    //         <a href="https://github.com/MijaelFV">
    //             <Image src={"/assets/github.svg"} height={30} width={30} className="cursor-pointer" alt="github profile" />
    //         </a>
    //     </div>
    // </div>

    const { progress } = useProgress();

    return (
        <div>
            <Head>
                <title>Portfolio Mijael</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex flex-col items-center">
                <div className="transition-all w-full" style={{opacity: progress < 95 ? 0 : 1}}>
                    <Hero />
                    <About />
                    <Skills />
                    <Portfolio />
                </div>
            </main>
            <footer>
            </footer>
        </div>
    )
}
